### ISSUE TITLE
Create option for ignoring shadow DOM action expected screens.

### ISSUE THREAD

**Issue by patchworksapp** [zacfilan/brimstone-recorder#110]
Right now shadowDOM screenshots are completely ignored for playback, but I still may want to time these operations. In order to do that I would need to be able to look at some portion of the screen.

Add an option so that different tests can choose to ignore shad DOM or not.

**Comment by zacfilan** [comment]
This can be done after the fact by unclicking shadow DOM in the step after the change. The only reason to do this is if you want perf numbers for it. Else it's probably better that the recorded test immediately passes. It's annoying to have to fix that immeditately.
