### ISSUE TITLE
How to take a screenshot when the user single clicks.

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#13]
A single click user action generates a sequence of events: mousedown, mouseup, click. Mousedown will generally also change focus to the current element, make it the active element, and blur whatever element had focus before.

While recording we just screenshot *just before* the user presses mousedown. 

# Option 1: Capture mousedown
*not currently used*

Capture mousedown, take the pic then drive just the mousedown event. This requires queuing events up then releasing them after mousedown is driven. 

Unfortunately, I am unable to completely block other mousedown related handling via preventDefault(), stopPropagation(), and stopImmediatePropagation(). Some other handler can add classes or styles to this element before I screenshot. (Perhaps I can use [this](https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-setIgnoreInputEvents) somehow in the future.)

In paticular, I cannot stop :active state styles from being applied, even when we "capture" mousedown. Why? Because [it's not defined](https://www.nickhart.co.uk/2019/03/12/unusual-behaviour-in-firefox-when-using-preventdefault/). Too bad this isn't a firefox extension. 

For :active styles using this approach would require me to remove the :active pseudo class programmatically. There are a few techniques I could try:

1. blur the element just before I grab the screenshot
2. clone, remove, add clone, screenshot, remove clone, add original element back,

# Option 2: Capture click 

*this is the implementation as of 7/16/2021*

Block (capture) all user action generated events that could change the screen. When I capture click, take screenshot then simulate the click, with the events all unblocked. The :active styling will still be applied on mousedown. The screenshot is taken after mouseup and click. The element may still be :active. However, this works for elements which look the same before mousedown and after mouseup. This works "ok" for most buttons.

This approach fails on "toggle-styled" element/button. Items which persist a styling change after the click event will store that as the expected (pre-click) screen state which is incorrect. Subsequently, during playback the screens will mismatch. The only workaround for now is to mark that as an allowable pixel difference.

# Option 3: Capture click use CSS to clear :active styles
*not currently used*

This only helps when the style change is because of :active, and doesn't fix the issue raised in option 2 above. 

Inject a new 'unset-active' css ruleset (once) into the page that unsets all :active styles I can think of. Block (capture) all user action generated events that could change the screen. When click is captured, add attribute(s) to the element to make this rule have highest precedence. Take screenshot, remove attributes that overwrote css, simulate the click.

**Comment by patchworksapp** [comment]
closed. moved to wiki
