### ISSUE TITLE
add a menu option to build a one page summary of error

### ISSUE THREAD

**Issue by patchworksapp** [zacfilan/brimstone-recorder#178]
This should be one html page or image that shows
expected: version info of the run. + image 
actual: version info of the run. + image
difference image.

**Comment by zacfilan** [comment]
* i want to be able "it looked like this in version 10, but then like this in version 11".
* so i must have two configurations per step. one is stored with the test. this must be updateable every time that the action is dirty and then saved. the other corresponds to the current run, that has not bee saved yet.
* i need a way to NOT save until I have given the user a chance to make an error report - confirm dialogs?

**Comment by zacfilan** [comment]
first draft is in - it just gives a summary of the currently displayed step (which if in error is what we want to share)
