### ISSUE TITLE
1.24.1 check-in - lost keyboard functions

### ISSUE THREAD

**Issue by pputre** [zacfilan/brimstone-recorder#239]
Hi Zac- login script for TW lost the ability to execute the 'Enter' command after typing in the password. All login scripts are failing that use this.  Still works on version 1.24.0
Here is the Json description in that step:
type password01<span class='modifier'>Enter</span>

Other steps that use the keyboard enter command seem to be working.  I will continue to research.  Let me know if you need any of the files.

**Comment by patchworksapp** [comment]
Ok. I'll get that fixed up ASAP.

**Comment by patchworksapp** [comment]
Could you try recording over that one step? e.g. the one where you type password01Enter

I had to generalize the way enter keys are recorded and played back. So right now you've got the old record enter action using the new playback mechanism and they don't match up.

**Comment by pputre** [comment]
Issue fixed.
