### ISSUE TITLE
How to record user inputs from the keyboard.

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#24]
# Single key
Single key user inputs are characterized by keydown, keypress, keyup event sequence. The keypress event is only triggered on keys that 'show something'. e.g. The Ctrl key does **not** generate keypress. 

## Detection
Currently a keydown is assumed to be enough. It blocks all events while tit takes a screen shot then simulates the 3 event sequence. This must change.

# Chords

Chords are like Ctrl-a or Ctrl-a-delete. These generate n keydowns followed by n keyups. If you follow the behavior of the browser on Ctrl-a (to 'copy-all') Ctrl keydown, a keydown is when the UI changes and highlights the screen. It stays highlighted on the two corresponding keyups.

## Detection

It is reassuring to block everything I can and only simulate, as that raises confidence that playback will work as expected.

### Option 1: Queue and release

Capture and queue every keydown, keypress, keyup. Simulate them individually. But to do this, I'd need to to queue them all, and let them lag a little bit behind the user. That could work in general. *In order to do that though I would require a way to tell events driven by the player (simulated) from those generated by native user inputs - timestamp encoding?*

### Option 1: Passive

Let the user inputs bubble, but recognize the pattern of keydowns and keyups. Then when it is completed, send the recorded observation. This requires screenshot on keydown, and then when all the keyups are complete record a chord user input. For Ctrl-a this will be handled by screenshot on Ctrl keydown, then on 'a' keydown the text will highlight, then on keyups, nothing happens. The user would clear it with a subsequent keypress like Delete.

### Option 2: Block and analyze

All events generated by the user inputs are blocked, and analyzed. When analysis determines the aggregate user action, that is recorded and simulated. For the chord Ctrl-a this would be two keydowns followed by two keyups. Then screenshot and simulate.

**Comment by patchworksapp** [comment]
closing moving to wiki
