### ISSUE TITLE
Need license file

### ISSUE THREAD

**Issue by nsreed** [zacfilan/brimstone-recorder#243]
I would love to fork & contribute to this plugin, but there isn't a license file. I'm not sure if I'm allowed to use this in a commercial pipeline, or what my rights are as a contributor.

As it stands, copyright law assume the de-facto license is all rights reserved to the original author. It would be awesome to see a MIT/Apache or GNU Affero General Public License version 3 (AGPL-v3) on this project!

I'd like to integrate Brimstone tests with PANIC https://github.com/gundb/panic-server to test peer-to-peer applications. This might entail adding additional input event capture features and/or more precise timing/replay capabilities. However, until the licensing is sorted, I can but sit on my quandaries and squaddle.

**Comment by zacfilan** [comment]
I picked AGPL-v3, cause it seemed groovy.
