### ISSUE TITLE
Chrome Beta - Brimstone extension version missing/unknown and tests pop a message preventing suite tests from running back to back without intervention.  Chrome Production is OK.

### ISSUE THREAD

**Issue by pputre** [zacfilan/brimstone-recorder#251]
When launching BR ext from current Chrome Beta version , the extension does not know what version it is running:
![image](https://user-images.githubusercontent.com/107417784/218794702-9c4682ba-6466-4f74-a936-7dd0be6091b1.png)
The tool/exstension looks like this in lower corner:
![image](https://user-images.githubusercontent.com/107417784/218795088-7be4d749-c05c-4baf-85ae-67d0c276e35f.png)
When running a test this message appears:
![image](https://user-images.githubusercontent.com/107417784/218795359-43a9928c-5308-42f9-b5a9-2f65443926ac.png)

**Comment by pputre** [comment]
I un-installed the extension and re-added . This fixed the issue

**Comment by patchworksapp** [comment]
I'll close this since you found a work around. I will also add  a checkbox to "ignore this from now on" so to make it easier.
