### ISSUE TITLE
window managment for recording and playback 

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#39]
# Recording

*Current implementation 8/2/2021* 

When the workspace is opened it is bound to the tab that it was opened from. Any recordings performed are
done on that one tab. 

# Playback

*Current implementation 8/2/2021* 

When the workspace is opened it is bound to the tab that it was opened from. Any recordings performed are
done on that one tab. 

# Issues

* #27
* Cannot support multi-tab/multi-window recordings. 
* Can't switch a non-incognito tab into an incognito tab. #38 

# Change Proposed

* When the workspace is first opened it is bound to the window, and the tab. 
* When recording started we use the tab.
    *  Send a mesage to see if the tab already has a recorder installed to prevent dups.
* When playing back we detect the mode desired, incognito or not and if that doesn't match the bound tab open a new one.

**Comment by patchworksapp** [comment]
closed moving to wiki
