### ISSUE TITLE
support multi window recordings.

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#40]
If a user action opens another tab/window from the active tab currently being recorded, then I want to be able to handle that.

I must know:
* when tabs open
* when tabs close
* when tab focus changes
* what the active tab is (the one that the user action is being recorded in)

In order to playback a recording, I will need to associate each user action with a tab identifier.
The tab identifier needs to persist between sessions somehow. (url I guess?)

I will need the concept of a browser action, that mimics the user switching or closing tabs.

**Comment by patchworksapp** [comment]
fixed
