### ISSUE TITLE
Tell the difference between a debugger attached to the page and for actual debuggning.

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#5]
The chrome debugger api needs to be attached to the page to play or record. I want that to be handled automatically and not bother the user.

But when I have manually attached another debugger to the extension (or the page) I need to distinguish that from the above.

**Comment by patchworksapp** [comment]
i misunderstood this scenario. i don't need to distingush dev opened debugger from chrome.debugger.attached opened. i can just try a sendcommand and if it fails do the chrome.debugger.attach.
