### ISSUE TITLE
I broke scroll recording

### ISSUE THREAD

**Issue by zacfilan** [zacfilan/brimstone-recorder#96]
While I am here, I should fix the scroll recording horizontal and vertical with the slider. As well as supporting the wheel events which may conincidentally scroll.

Both of these require auto screenshots to record the end of the previous action. I will take the approach of a mousemove (??of at least x pixels, or any pixels??) followed by a blur/focus/mouseout/mouseover AFTER

1. the last recorded action acked/queue empty
2. a navigation completed

sufficient to trigger a screenshot to be taken.

**Comment by patchworksapp** [comment]
fixed with 8520b8b9d038183c92fd6e3c529ad319fcfb276e
